import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';
const commands=await readFile(new URL('../assets/crm-live-commands.js',import.meta.url),'utf8');
const code=(await readFile(new URL('../assets/crm-live.js',import.meta.url),'utf8')).replace("import {resolveCommand} from './crm-live-commands.js';",commands.replace('export function resolveCommand','function resolveCommand'));
test('Live controller uses local exact selection/scroll, one JEV fallback, explicit reply only and existing global dismissal; never sends',async()=>{
 const names=['document','window','matchMedia','navigator','AudioContext','AudioWorkletNode','WebSocket','MutationObserver','innerHeight','requestAnimationFrame','getComputedStyle'];const previous=Object.fromEntries(names.map(n=>[n,Object.getOwnPropertyDescriptor(globalThis,n)]));
 const nodes=[],requests=[],disposed=[],replies=[],drafts=[],scrolled=[],sent=[],documentHandlers={};let ws,stopped=false,denyAction=false;
 const node=()=>({handlers:{},dataset:{},isConnected:true,getClientRects:()=>[{}],getBoundingClientRect:()=>({width:300,height:200}),classList:{add(){},remove(){}},setAttribute(){},append(){},after(){},scrollIntoView(){},addEventListener(type,fn){this.handlers[type]=fn;}});
 const root=node(),head=node(),tabs=node(),mail=node(),targets=new Map([['gmail-12345678abcdefaa',node()],['gmail-12345678abcdefbb',node()]]);
 const cards=[{id:'gmail-12345678abcdefaa',lastMessageId:'a',title:'MX One consultation',tab:'sales'},{id:'gmail-12345678abcdefbb',lastMessageId:'b',title:'Alpha Insights',tab:'sales'}];let current={tab:'sales',cards};
 for(const[id,target]of targets)target.dataset.threadId=id.slice(6);
 try{
  Object.defineProperty(globalThis,'requestAnimationFrame',{configurable:true,value:fn=>setImmediate(fn)});Object.defineProperty(globalThis,'getComputedStyle',{configurable:true,value:()=>({outlineWidth:'3px',visibility:'visible',display:'block'})});
  Object.defineProperty(globalThis,'document',{configurable:true,value:{addEventListener(type,fn){documentHandlers[type]=fn;},createElement(){const n=node();nodes.push(n);return n;},querySelector(s){return s==='.workspace-actions'?root:s==='.workspace-head'?head:s==='.workspace-tabs'?tabs:mail;},querySelectorAll(){return[];}}});
  Object.defineProperty(globalThis,'window',{configurable:true,value:{addEventListener(){},scrollBy(v){scrolled.push(v);}}});Object.defineProperty(globalThis,'innerHeight',{configurable:true,value:800});Object.defineProperty(globalThis,'matchMedia',{configurable:true,value:()=>({matches:true})});
  Object.defineProperty(globalThis,'navigator',{configurable:true,value:{mediaDevices:{getUserMedia:async()=>({getTracks:()=>[{stop(){stopped=true;}}]})}}});
  Object.defineProperty(globalThis,'AudioContext',{configurable:true,value:class{constructor(){this.audioWorklet={addModule:async()=>{}};this.currentTime=0;}async resume(){}createMediaStreamSource(){return{connect(){return this;},disconnect(){}};}createGain(){return{gain:{value:0},connect(){return this;},disconnect(){}};}async close(){}}});
  Object.defineProperty(globalThis,'AudioWorkletNode',{configurable:true,value:class{constructor(){this.port={};}connect(){return this;}disconnect(){}}});
  Object.defineProperty(globalThis,'MutationObserver',{configurable:true,value:class{observe(){}}});
  Object.defineProperty(globalThis,'WebSocket',{configurable:true,value:class{static OPEN=1;constructor(){ws=this;this.readyState=1;setImmediate(()=>{this.onopen();this.onmessage({data:JSON.stringify({setupComplete:{}})});});}send(value){sent.push(JSON.parse(value));}close(){this.readyState=3;}}});
  const {mountLive}=await import('data:text/javascript;base64,'+Buffer.from(code).toString('base64'));
  const controller=mountLive({context:()=>current,target:id=>targets.get(id),api:async(path,body)=>{requests.push(path);if(denyAction&&path.endsWith('/validate')){documentHandlers['crm:auth-lost']();throw Object.assign(Error('Please reconnect Google. Nothing was changed or sent.'),{status:401});}if(path.endsWith('/session'))return{token:'auth_tokens/fixture',view:'fixture-view',setup:{}};if(path.endsWith('/identify'))return{id:cards[0].id,jevMs:12,providerRequests:1};return{view:'updated-view'};},reply:(id,intent)=>replies.push({id,intent}),replyOpen:()=>replies.length>0,dispose:async(id,action)=>{disposed.push({id,action});targets.delete(id);current={...current,cards:current.cards.filter(c=>c.id!==id)};},liveDraft:async(id,message)=>drafts.push({id,message})});
  nodes[0].handlers.click();await new Promise(resolve=>setImmediate(resolve));await new Promise(resolve=>setImmediate(resolve));
  assert.equal((await controller.command('second one')).highlighted,true);assert.equal(requests.filter(p=>p.endsWith('/identify')).length,0);assert.equal(replies.length,0);assert.equal(drafts.length,0);
  await ws.onmessage({data:JSON.stringify({serverContent:{inputTranscription:{text:'select Alpha '}}})});await ws.onmessage({data:JSON.stringify({serverContent:{inputTranscription:{text:'Insights'}}})});await ws.onmessage({data:JSON.stringify({toolCall:{functionCalls:[{id:'select',name:'workspace_command',args:{utterance:'select Alpha Insights'}}]}})});assert.equal(sent.at(-1).toolResponse.functionResponses[0].response.highlighted,true,'tool bridge reports the actual accumulated spoken selection, not a made-up acknowledgment');await ws.onmessage({data:JSON.stringify({serverContent:{outputTranscription:{text:'Done.'},turnComplete:true}})});
  assert.equal((await controller.command('go to it')).highlighted,true);assert.equal(replies.length,0);assert.equal(disposed.length,0);const missing=targets.get(cards[1].id);targets.delete(cards[1].id);assert.ok((await controller.command('select Alpha Insights')).error);targets.set(cards[1].id,missing);
  await controller.command('scroll down a bit');assert.equal(scrolled[0].top,680);
  await controller.command('mxone');assert.equal(requests.filter(p=>p.endsWith('/identify')).length,0,'compact known names stay local');await controller.command('the advisor session');assert.equal(requests.filter(p=>p.endsWith('/identify')).length,1);
  await controller.command('reply to it with thank you for the invitation');assert.equal(replies.length,1);assert.equal(drafts.length,0,'opening a reply never generates');
  await ws.onmessage({data:JSON.stringify({toolCall:{functionCalls:[{id:'draft',name:'draft_reply',args:{message:'Thank you for the invitation.'}}]}})});assert.equal(drafts.length,1);
  const earlyDoneTool=ws.onmessage({data:JSON.stringify({toolCall:{functionCalls:[{id:'done',name:'workspace_command',args:{utterance:'Done.'}}]}})});await new Promise(resolve=>setImmediate(resolve));assert.equal(disposed.length,0,'early tool call must not reuse the previous selection utterance');await ws.onmessage({data:JSON.stringify({serverContent:{inputTranscription:{text:'Done.'}}})});await earlyDoneTool;const done=sent.at(-1).toolResponse.functionResponses[0].response;assert.equal(disposed.length,1);assert.equal(disposed[0].action,'done');assert.equal(done.nextSelected,true);assert.equal(done.nextId,cards[1].id);assert.equal(done.say,'Marked the MX mail done. Next: the Alpha mail.');assert.equal(done.selectedId,cards[1].id);assert.equal((await controller.command('select it')).id,cards[1].id);await ws.onmessage({data:JSON.stringify({serverContent:{turnComplete:true}})});
  // A new transcript must not acknowledge the previous Done or execute its fragments.
  await ws.onmessage({data:JSON.stringify({serverContent:{inputTranscription:{text:'Reply'}}})});assert.equal(replies.length,1,'transcript fragments do not invoke actions');await ws.onmessage({data:JSON.stringify({serverContent:{turnComplete:true}})});assert.equal(replies.length,2,'completed direct speech dispatches even if the model omits workspace_command');assert.equal(replies.at(-1).id,cards[1].id);assert.equal(nodes[1].dataset.actionEffect,'reply-open');assert.equal(nodes[1].textContent,'Replying to the Alpha mail. What should I say?');const sendsBefore=sent.length;await ws.onmessage({data:JSON.stringify({serverContent:{outputTranscription:{text:'Done.'},turnComplete:true}})});assert.equal(sent.length,sendsBefore,'unsolicited Done cannot reuse a prior action result');
  await controller.command('send it');assert.ok(!requests.some(p=>p.includes('send')));assert.equal(drafts.length,1);
  await ws.onmessage({data:JSON.stringify({serverContent:{inputTranscription:{text:'Do not mark it done.'}}})});await ws.onmessage({data:JSON.stringify({toolCall:{functionCalls:[{id:'unsafe',name:'workspace_command',args:{utterance:'Mark it as done.'}}]}})});assert.equal(disposed.length,1,'a model tool cannot turn negated speech into a dismissal');await ws.onmessage({data:JSON.stringify({serverContent:{turnComplete:true}})});
  denyAction=true;await ws.onmessage({data:JSON.stringify({serverContent:{inputTranscription:{text:'Market is done.'}}})});await ws.onmessage({data:JSON.stringify({toolCall:{functionCalls:[{id:'asr-repair',name:'workspace_command',args:{utterance:'Mark it as done.'}}]}})});assert.equal(disposed.length,1,'expired auth never disposes the card');assert.equal(stopped,true,'expired auth stops microphone');assert.equal(ws.readyState,3);assert.equal(nodes[1].dataset.selectionConfirmed,'false');assert.equal(nodes[1].dataset.selectedCardId,undefined);assert.equal((await controller.command('mark it done')).error,'Live is not connected.');
  current={tab:'jobs',cards:[]};await controller.command('second one');assert.equal(disposed.length,1,'old selection cannot mutate a new tab');controller.stop();assert.equal(stopped,true);
 }finally{for(const name of names){if(previous[name])Object.defineProperty(globalThis,name,previous[name]);else delete globalThis[name];}}
});
