import test from 'node:test';import assert from 'node:assert/strict';import {createWorkspaceFlow} from '../scripts/crm-workspace-flow.mjs';import {crmSecurityForTests as security} from '../scripts/crm-api.mjs';
test('one encrypted shared fetch serves every tab; cache restoration and analysis never reread Gmail; concurrent owner fetches are blocked',async()=>{
 const originalFetch=globalThis.fetch,priorKey=process.env.TYPESAFE_API_KEY;process.env.TYPESAFE_API_KEY='fixture';const docs=new Map(),config={key:Buffer.alloc(32,9),sessionSecret:'x'.repeat(40)};let googleCalls=0,modelCalls=0,listQuery='',release;const gate=new Promise(resolve=>release=resolve);const ids=['12345678abcdefaa','12345678abcdefbb'];
 const deps={...security,storedList:async(uid,collection)=>[...docs].filter(([p])=>p.startsWith(`${uid}/${collection}/`)).map(([p,r])=>({id:p.split('/').at(-1),...r})),firestore:async(path,method='GET',fields,version)=>{if(method==='PATCH'){const old=docs.get(path);if(version==='missing'&&old || version&&version!=='missing'&&old?.updateTime!==version)throw Object.assign(Error('precondition'),{status:409});docs.set(path,{...fields,updateTime:String(Number(old?.updateTime||0)+1)});}return docs.get(path)||null;},googleRequest:async(uid,user,config,url)=>{googleCalls++;if(url.includes('/threads?')){listQuery=new URL(url).searchParams.get('q');await gate;return{threads:ids.map(id=>({id}))};}const id=url.split('/threads/')[1].split('?')[0];return{id,messages:[{id:`m-${id}`,internalDate:String(Date.now()-(id===ids[0]?3:10)*86400000),payload:{mimeType:'text/plain',headers:[{name:'Subject',value:'Source fixture'},{name:'From',value:'peer@example.test'}],body:{data:Buffer.from('Please review this source-only request.').toString('base64url')}}}]};}};
 globalThis.fetch=async(url,options)=>{assert.match(String(url),/typesafe.ai/);modelCalls++;const body=JSON.parse(options.body);return new Response(JSON.stringify({answers:Object.fromEntries(Object.keys(body.questions).map(k=>[k,{choice:'theme_0',confidence:.98,probabilities:{theme_0:.99,theme_1:.01}}]))}));};
 try{
  const first=createWorkspaceFlow(deps),second=createWorkspaceFlow(deps),fetching=first.run('fetch','alice',{email:'owner@example.test'},config,{tab:'sales'});await new Promise(resolve=>setImmediate(resolve));
  await assert.rejects(second.run('fetch','alice',{email:'owner@example.test'},config,{tab:'finance'}),/already fetching/);release();const fetched=await fetching;
  assert.equal(fetched.shared,true);assert.equal(modelCalls,0);assert.equal(fetched.items.length,2);assert.ok(Number(listQuery.match(/after:(\d+)/)[1])<=Math.floor((Date.now()-14*86400000)/1000)+1);assert.ok(!listQuery.includes('application'));
  const beforeGoogle=googleCalls,cache=await second.cache('alice',config);assert.equal(cache.items.length,2);assert.equal(modelCalls,0);assert.equal(googleCalls,beforeGoogle);assert.equal(await second.cache('bob',config),null);
  for(const[tab,count]of Object.entries({sales:1,actions:1,finance:1,jobs:2,clusters:2})){
   const result=await second.run('analyze','alice',{email:'owner@example.test'},config,{tab,fetchId:cache.fetchIds[tab]});assert.equal(result.scanned,count,tab);assert.equal(result.timings.geminiRequests,0);assert.equal(googleCalls,beforeGoogle,'switching tabs/analyzing never refetches');
  }
 }finally{release();globalThis.fetch=originalFetch;if(priorKey===undefined)delete process.env.TYPESAFE_API_KEY;else process.env.TYPESAFE_API_KEY=priorKey;}
});
