import {validateScenario} from './daily-scenarios.mjs';
const literal=s=>`'${String(s).replaceAll("'","''")}'`;
export async function appendDay(c,date,scenario){
 if(!/^\d{4}-\d{2}-\d{2}$/.test(date)||new Date(date+'T12:00:00Z').toISOString().slice(0,10)!==date)throw Error('Invalid date');validateScenario(scenario);
 const one=async sql=>(await c.runAndReadAll(sql)).getRowObjectsJson()[0];
 await c.run('CREATE TABLE IF NOT EXISTS generation_runs (date DATE PRIMARY KEY, model VARCHAR, scenario_json VARCHAR, generated_at TIMESTAMP)');
 if(Number((await one(`SELECT count(*) n FROM generation_runs WHERE date=DATE '${date}'`)).n))return {date,skipped:true};
 const last=await one('SELECT max(order_date)::VARCHAR date FROM orders');if(last.date>=date)throw Error('Refusing overlapping or out-of-order day');
 const ids=await one('SELECT (SELECT coalesce(max(order_id),0) FROM orders) orders,(SELECT coalesce(max(order_item_id),0) FROM order_items) items,(SELECT coalesce(max(session_id),0) FROM sessions) sessions,(SELECT coalesce(max(event_id),0) FROM business_events) events,(SELECT count(*) FROM products) products,(SELECT count(*) FROM customers) customers');
 const baselines=await one(`SELECT (SELECT count(*)/28.0 FROM orders WHERE order_date > DATE '${last.date}'-28) orders,(SELECT count(*)/28.0 FROM sessions WHERE session_date > DATE '${last.date}'-28) sessions`);
 const n=Math.max(100,Math.round(baselines.orders*scenario.volumeFactor)),traffic=Math.max(n+100,Math.round(baselines.sessions*(.8+.2*scenario.paidTrafficFactor))),seed=Number(date.replaceAll('-',''));const price=scenario.priceFactor*(1-scenario.promotionPct/100);
 await c.run('BEGIN TRANSACTION');
 try{
 await c.run(`CREATE TEMP TABLE new_items AS SELECT (${ids.items}+i)::INTEGER order_item_id,(${ids.orders}+1+((i-1)//3))::INTEGER order_id,p.product_id,(1+hash(i+${seed})%3)::INTEGER quantity,round(p.list_price*${scenario.priceFactor},2)::DECIMAL(12,2) unit_price,round(unit_price*quantity*${scenario.promotionPct}/100,2)::DECIMAL(12,2) discount_amount,(unit_price*quantity-discount_amount)::DECIMAL(12,2) net_amount FROM range(1,${n*3+1})t(i) JOIN products p ON p.product_id=1+hash(i+${seed}+211)%${ids.products}`);
 await c.run(`INSERT INTO order_items SELECT * FROM new_items`);
 await c.run(`CREATE TEMP TABLE new_orders AS SELECT order_id,(1+hash(order_id+${seed}+307)%${ids.customers})::INTEGER customer_id,DATE '${date}' order_date,list_extract(['web','mobile_app','marketplace'],(1+hash(order_id+${seed})%3)::BIGINT) channel,CASE WHEN hash(order_id+${seed}+373)%100 < CASE WHEN hash(order_id+${seed})%3=1 THEN ${scenario.mobileCancellationPct} ELSE 5 END THEN 'cancelled' WHEN hash(order_id+${seed}+373)%100<12 THEN 'returned' ELSE 'completed' END status,sum(net_amount)::DECIMAL(14,2) net_amount,round(sum(net_amount)*.08,2)::DECIMAL(14,2) tax_amount,(CASE WHEN sum(net_amount)>=150 THEN 0 ELSE 6.99 END)::DECIMAL(12,2) shipping_amount FROM new_items GROUP BY order_id`);
 await c.run('INSERT INTO orders SELECT * FROM new_orders');
 await c.run(`INSERT INTO payments SELECT order_id,order_id,order_date,list_extract(['card','wallet','bank_transfer'],(1+hash(order_id+397)%3)::BIGINT),CASE WHEN status='cancelled' THEN 'void' WHEN status='returned' THEN 'refunded' ELSE 'captured' END,(net_amount+tax_amount+shipping_amount)::DECIMAL(14,2) FROM new_orders`);
 await c.run(`INSERT INTO shipments SELECT order_id,order_id,order_date+1,order_date+(2+hash(order_id+419)%6)::INTEGER,list_extract(['Standard','Express','Economy'],(1+hash(order_id+433)%3)::BIGINT),CASE WHEN status='returned' THEN 'returned' WHEN status='cancelled' THEN 'cancelled' ELSE 'delivered' END FROM new_orders WHERE hash(order_id)%100<85`);
 await c.run(`INSERT INTO sessions SELECT (${ids.sessions}+i)::INTEGER,CASE WHEN i<=${n} THEN o.customer_id ELSE (1+hash(i+${seed}+461)%${ids.customers})::INTEGER END,DATE '${date}',CASE WHEN hash(i+${seed}+503)%100<${20*scenario.paidTrafficFactor} THEN 'paid_search' ELSE list_extract(['organic','social','email','direct'],(1+hash(i+${seed}+505)%4)::BIGINT) END,CASE WHEN i<=${n} AND o.channel='mobile_app' THEN 'mobile' ELSE list_extract(['desktop','mobile','tablet'],(1+hash(i+${seed}+521)%3)::BIGINT) END,(1+hash(i+${seed}+541)%18)::INTEGER,CASE WHEN i<=${n} THEN o.order_id ELSE NULL END FROM range(1,${traffic+1})t(i) LEFT JOIN new_orders o ON o.order_id=${ids.orders}+i`);
 await c.run(`INSERT INTO calendar SELECT DATE '${date}',year(DATE '${date}'),month(DATE '${date}'),day(DATE '${date}'),strftime(DATE '${date}','%A'),quarter(DATE '${date}') WHERE NOT EXISTS(SELECT 1 FROM calendar WHERE date=DATE '${date}')`);
 await c.run(`INSERT INTO business_events VALUES (${ids.events+1},${literal(scenario.kind)},'generated daily scenario',DATE '${date}',DATE '${date}','Demo markets',${literal(scenario.kind)},${Math.round((scenario.volumeFactor*price-1)*10000)/100},${literal(scenario.summary)},'synthetic scenario')`);
 await c.run(`INSERT INTO market_snapshots SELECT DATE '${date}',market,competitor,category_group,${scenario.promotionPct}>0,round(sampled_price_index*(1-${scenario.promotionPct}/300),2),${scenario.promotionPct},products_sampled,${literal(scenario.promotionPct?'Modeled daily promotion':'Modeled normal trading')},'synthetic benchmark sample' FROM market_snapshots WHERE snapshot_date=DATE '${last.date}'`);
 await c.run(`INSERT INTO generation_runs VALUES (DATE '${date}',${literal(scenario.model||'test-fixture')},${literal(JSON.stringify(scenario))},current_timestamp)`);
 const check=await one(`SELECT count(*) n FROM new_orders o JOIN (SELECT order_id,sum(net_amount) amount FROM new_items GROUP BY order_id)i USING(order_id) WHERE o.net_amount<>i.amount`);if(Number(check.n))throw Error('Order totals do not reconcile');
 await c.run('DROP TABLE new_orders; DROP TABLE new_items; COMMIT');return {date,orders:n,sessions:traffic};
 }catch(e){await c.run('ROLLBACK');throw e;}
}
