steps:
  - name: gcr.io/cloud-builders/docker
    args: ['build', '-f', 'server/Dockerfile', '--build-arg', 'DEMO_SCALE=1', '-t', 'europe-west1-docker.pkg.dev/striking-loop-447915-q3/cloud-run-source-deploy/liveanalyst-duckdb:10m-v5', '.']
  - name: gcr.io/cloud-builders/docker
    args: ['run', '--rm', '--cpus=2', '--memory=2g', '-e', 'EXPECTED_ROWS=10000000', 'europe-west1-docker.pkg.dev/striking-loop-447915-q3/cloud-run-source-deploy/liveanalyst-duckdb:10m-v5', 'node', 'server/benchmark.mjs']
images:
  - europe-west1-docker.pkg.dev/striking-loop-447915-q3/cloud-run-source-deploy/liveanalyst-duckdb:10m-v5
options:
  machineType: E2_HIGHCPU_8
