steps:
  - name: gcr.io/cloud-builders/docker
    args: ['build', '-f', 'server/Daily.Dockerfile', '-t', 'europe-west1-docker.pkg.dev/striking-loop-447915-q3/cloud-run-source-deploy/liveanalyst-duckdb:daily-20261008', '.']
images:
  - europe-west1-docker.pkg.dev/striking-loop-447915-q3/cloud-run-source-deploy/liveanalyst-duckdb:daily-20261008
