import {planQuery} from './demo-planner.mjs';
const target='https://liveanalyst-duckdb-648674198172.europe-west1.run.app';
const origins=new Set(['https://decisionos.me','https://www.decisionos.me','https://decisionaxis.co','https://www.decisionaxis.co','https://meridian-live-analytics.aditya-vithaldas.chatgpt.site','http://localhost:4173','http://localhost:3000']);
let identity=null,identityUntil=0,metadata=null,metadataUntil=0,active=0;const perIP=new Map();let day='',daily=0;
async function privateCall(path,body){if(Date.now()>identityUntil){const r=await fetch('http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/identity?audience='+encodeURIComponent(target),{headers:{'Metadata-Flavor':'Google'},signal:AbortSignal.timeout(5000)});if(!r.ok)throw Error('Database authentication unavailable');identity=await r.text();identityUntil=Date.now()+45*60000;}const r=await fetch(target+path,{method:body?'POST':'GET',headers:{Authorization:'Bearer '+identity,...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{}),signal:AbortSignal.timeout(12000)});const d=await r.json();if(!r.ok)throw Error(d.error||'Database unavailable');return d;}
const send=(res,status,body)=>res.headersSent?res.end(JSON.stringify({type:status===200?'result':'error',...body})+'\n'):res.writeHead(status,{'Content-Type':'application/json','Cache-Control':'no-store'}).end(JSON.stringify(body));
export function explainResults(plan,points){
 const fmt=n=>new Intl.NumberFormat('en-US',{maximumFractionDigits:plan.unit==='%'?2:0,...(plan.unit==='USD'?{style:'currency',currency:'USD'}:{})}).format(n)+(plan.unit==='%'?'%':'');
 if(plan.analysis==='contribution'||plan.analysis==='comparison'){
  const paired=points.filter(p=>Number.isFinite(p.secondary));
  if(paired.length){const drivers=[...paired].sort((a,b)=>Math.abs(b.value-b.secondary)-Math.abs(a.value-a.secondary)).slice(0,3);return drivers.map(p=>`${p.label}: ${fmt(p.value)}, ${p.value>=p.secondary?'up':'down'} ${fmt(Math.abs(p.value-p.secondary))} from ${fmt(p.secondary)}`).join('; ')+'. These are measured contributions, not proof of cause.';}
 }
 if(points.length===1)return `${points[0].label}: ${fmt(points[0].value)}.`;
 if(plan.analysis==='trend'){const a=points[0],b=points.at(-1);return `From ${a.label} to ${b.label}, the value moved from ${fmt(a.value)} to ${fmt(b.value)} (${b.value>=a.value?'up':'down'} ${fmt(Math.abs(b.value-a.value))}).`;}
 const top=[...points].sort((a,b)=>b.value-a.value).slice(0,3);return 'Leading results: '+top.map(p=>`${p.label} (${fmt(p.value)})`).join(', ')+'.';
}
export async function demoAPI(req,res){const origin=req.headers.origin;if(origins.has(origin)){res.setHeader('Access-Control-Allow-Origin',origin);res.setHeader('Vary','Origin');res.setHeader('Access-Control-Allow-Headers','Content-Type');res.setHeader('Access-Control-Allow-Methods','GET,POST,OPTIONS');}if(req.method==='OPTIONS'){res.writeHead(origins.has(origin)?204:403).end();return;}const path=new URL(req.url,'http://localhost').pathname;
 try{if(!metadata||Date.now()>metadataUntil){metadata=await privateCall('/metadata');metadataUntil=Date.now()+60000;}if(req.method==='GET'&&/\/(metadata|schema)$/.test(path))return send(res,200,metadata);if(req.method!=='POST'||!path.endsWith('/query'))return send(res,405,{error:'Use POST'});if(!origins.has(origin))return send(res,403,{error:'Invalid origin'});const today=new Date().toISOString().slice(0,10);if(today!==day){day=today;daily=0;}const now=Date.now(),ip=req.headers['x-forwarded-for']?.split(',')[0]||req.socket.remoteAddress;for(const[k,v]of perIP)if(now-v.at>60000)perIP.delete(k);const b=perIP.get(ip)||{at:now,n:0};if(++b.n>15||daily>=1000||active>=2)return send(res,429,{error:'This demo is busy. Please try again shortly.'});perIP.set(ip,b);let raw='';for await(const chunk of req){raw+=chunk;if(raw.length>100000)return send(res,413,{error:'Request too large'});}const {message,context,stream}=JSON.parse(raw);if(typeof message!=='string'||!message.trim()||message.length>3000)return send(res,400,{error:'Please use a shorter question.'});daily++;active++;const started=performance.now();const stage=(step,detail)=>{if(stream===true)res.write(JSON.stringify({type:'stage',step,detail})+'\n');};if(stream===true){res.writeHead(200,{'Content-Type':'application/x-ndjson','Cache-Control':'no-store','X-Accel-Buffering':'no'});res.flushHeaders();}try{stage(1,'Reading the schema and converting your question into SQL.');const plan=await planQuery(message,context,metadata);stage(2,plan.sql);const result=await privateCall('/query',{sql:plan.sql});stage(3,`Analyzing ${result.rows.length} result rows for ${plan.title}.`);const points=result.rows.map(r=>{if(r.label===undefined||r.value===undefined||!Number.isFinite(Number(r.value)))throw Error('Invalid query result');return {label:String(r.label),value:Number(r.value),...(r.secondary!==undefined?{secondary:Number(r.secondary)}:{})};});if(!points.length)throw Error('No matching demo records. Try a different date or filter.');return send(res,200,{mode:'replace',display:plan.display,generated:{title:plan.title,label:plan.title,period:plan.period||'2025',unit:plan.unit,aggregation:'sum',kind:plan.kind,axisType:plan.axisType,points,explanation:explainResults(plan,points),...(points[0].secondary!==undefined?{secondaryLabel:plan.secondaryLabel||'Previous period'}:{})},sql:plan.sql,metrics:{planningMs:plan.planningMs,sqlMs:result.sqlMs,serverMs:performance.now()-started,planCacheHit:plan.planCacheHit},dataset:{rows:metadata.totalRows,bytes:metadata.databaseBytes}});}finally{active--;}}catch(e){return send(res,400,{error:e.message});}}
