import assert from 'node:assert/strict';
import {DuckDBInstance} from '../server/node_modules/@duckdb/node-api/lib/DuckDBInstance.js';
import {copyFile,mkdir} from 'node:fs/promises';
import {appendDay} from '../server/append-day.mjs';
import {yesterdayBerlin,validateScenario} from '../server/daily-scenarios.mjs';
import {decompose} from '../server/mcp/intelligence.mjs';
assert.equal(yesterdayBerlin(new Date('2026-10-25T23:30:00Z')),'2026-10-25');
assert.equal(yesterdayBerlin(new Date('2026-03-29T22:30:00Z')),'2026-03-29');
assert.throws(()=>validateScenario({kind:'sql_injection'}));
const folder=process.env.TEST_DATA_DIR;assert.ok(folder,'TEST_DATA_DIR required');await mkdir(folder,{recursive:true});await copyFile(process.env.BASE_DATA_DIR+'/ecommerce.duckdb',folder+'/test.duckdb');
const db=await DuckDBInstance.create(folder+'/test.duckdb');const c=await db.connect();const scenario={kind:'mobile_checkout',volumeFactor:1,priceFactor:1,paidTrafficFactor:1,mobileCancellationPct:25,promotionPct:0,summary:'Modeled mobile checkout friction',model:'test-fixture'};
await appendDay(c,'2026-09-30',scenario);const repeat=await appendDay(c,'2026-09-30',scenario);assert.equal(repeat.skipped,true);
await assert.rejects(()=>appendDay(c,"2026-09-30';DROP TABLE orders--",scenario));
const one=async sql=>{const r=(await c.runAndReadAll(sql)).getRowObjectsJson()[0];if('n' in r)r.n=Number(r.n);return r;};
for(const [table,column,target,id]of [['order_items','order_id','orders','order_id'],['orders','customer_id','customers','customer_id'],['order_items','product_id','products','product_id'],['payments','order_id','orders','order_id'],['sessions','order_id','orders','order_id']])assert.equal((await one(`SELECT count(*) n FROM ${table} s LEFT JOIN ${target} t ON s.${column}=t.${id} WHERE s.${column} IS NOT NULL AND t.${id} IS NULL`)).n,0);
assert.equal((await one("SELECT count(*) n FROM orders o JOIN(SELECT order_id,sum(net_amount) amount FROM order_items GROUP BY order_id)i USING(order_id) WHERE o.order_date=DATE '2026-09-30' AND o.net_amount<>i.amount")).n,0);
assert.equal((await one("SELECT count(*) n FROM payments p JOIN orders o USING(order_id) WHERE o.order_date=DATE '2026-09-30' AND p.amount<>o.net_amount+o.tax_amount+o.shipping_amount")).n,0);
assert.equal((await one("SELECT count(*) n FROM sessions s JOIN orders o USING(order_id) WHERE s.session_date<>o.order_date")).n,0);
const effects=decompose({sessions:900,orders:80,revenue:7600},{sessions:1000,orders:100,revenue:10000});assert.ok(Math.abs(effects.unexplained)<1e-7);assert.equal(effects.effects.reduce((s,e)=>s+e.effect,0),-2400);
c.closeSync();db.closeSync();console.log('PASS: timezone/DST, invalid inputs, daily retry, foreign keys, revenue/payments, session dates, RCA reconciliation');
