'use client';
import {ArrowLeft,ArrowRight,Check,Database,FileSpreadsheet,FolderOpen,Server,ShieldCheck,X} from 'lucide-react';
import {FormEvent,useState} from 'react';

type Source='postgresql'|'mysql'|'duckdb'|'files';
const sources=[
 {kind:'postgresql' as Source,name:'PostgreSQL',detail:'Connect a read-only production or analytics database.',badge:'SQL'},
 {kind:'mysql' as Source,name:'MySQL',detail:'Profile an existing MySQL workspace in place.',badge:'SQL'},
 {kind:'duckdb' as Source,name:'DuckDB',detail:'Use a DuckDB file or the hosted commerce demo.',badge:'FILE'},
 {kind:'files' as Source,name:'Files & folders',detail:'Import CSV or Excel files and rebuild them as an analysis database.',badge:'IMPORT'}
];

export default function DataConnections({onClose,onFiles}:{onClose:()=>void;onFiles:(files:File[])=>void}){
 const [source,setSource]=useState<Source>('postgresql'),[step,setStep]=useState<'source'|'connection'|'ready'>('source');
 const [host,setHost]=useState(''),[database,setDatabase]=useState(''),[username,setUsername]=useState(''),[files,setFiles]=useState<File[]>([]);
 const selected=sources.find(item=>item.kind===source)!;
 function choose(next:Source){setSource(next);setFiles([]);}
 function submit(event:FormEvent){event.preventDefault();if(source==='files'){onFiles(files);onClose();return;}setStep('ready');}
 return <div className="dc-backdrop" role="presentation" onMouseDown={event=>{if(event.currentTarget===event.target)onClose();}}><section className="dc-modal" role="dialog" aria-modal="true" aria-labelledby="dc-title"><header><div><Database size={18}/><strong>Connect your data</strong></div><button aria-label="Close data connections" onClick={onClose}><X size={20}/></button></header>
  {step==='source'?<main><p className="dc-eyebrow">DATA SOURCES</p><h2 id="dc-title">Where should Meridian look?</h2><p className="dc-intro">Connect a database in place, or turn files and project folders into an analysis workspace.</p><div className="dc-source-grid" role="radiogroup">{sources.map(item=><button key={item.kind} role="radio" aria-checked={source===item.kind} className={source===item.kind?'is-selected':''} onClick={()=>choose(item.kind)}><span className="dc-icon">{item.kind==='files'?<FolderOpen size={21}/>:item.kind==='duckdb'?<FileSpreadsheet size={21}/>:<Server size={21}/>}</span><span><strong>{item.name}</strong><small>{item.detail}</small></span><em>{item.badge}</em>{source===item.kind&&<Check className="dc-check" size={15}/>}</button>)}</div><footer><span>Source rows remain under your control.</span><button className="dc-primary" onClick={()=>setStep('connection')}>Continue with {selected.name} <ArrowRight size={16}/></button></footer></main>:
  step==='connection'?<form onSubmit={submit}><button type="button" className="dc-back" onClick={()=>setStep('source')}><ArrowLeft size={15}/> Change source</button><p className="dc-eyebrow">{selected.name.toUpperCase()}</p><h2 id="dc-title">Connect your data.</h2>{source==='files'?<label className="dc-file"><FolderOpen size={24}/><strong>Choose files or a project folder</strong><small>CSV and Excel files from one commerce dataset</small><input type="file" accept=".csv,.xlsx,.xls" multiple onChange={event=>setFiles(Array.from(event.target.files||[]))}/>{files.length>0&&<span>{files.length} file{files.length===1?'':'s'} selected</span>}</label>:source==='duckdb'?<div className="dc-duck"><Database size={28}/><div><strong>Hosted commerce demo</strong><small>Use the current European commerce workspace, or choose a DuckDB file.</small></div><label>Choose DuckDB file<input type="file" accept=".duckdb,.db" onChange={event=>setFiles(Array.from(event.target.files||[]))}/></label></div>:<div className="dc-form-grid"><label className="dc-wide">Host<input placeholder="analytics.example.com" value={host} onChange={event=>setHost(event.target.value)} required/></label><label>Port<input inputMode="numeric" defaultValue={source==='postgresql'?'5432':'3306'} required/></label><label>Database<input placeholder="commerce" value={database} onChange={event=>setDatabase(event.target.value)} required/></label><label>Username<input autoComplete="username" placeholder="meridian_reader" value={username} onChange={event=>setUsername(event.target.value)} required/></label><label>Password<input type="password" autoComplete="current-password"/></label></div>}<div className="dc-note"><ShieldCheck size={18}/><span><strong>{source==='files'?'Workspace-contained import.':'Read-only by design.'}</strong> {source==='files'?'Files are profiled inside this browser workspace.':'Meridian stores schema, aggregate profiles, and learned definitions—not source rows.'}</span></div><footer><span>Meridian runs a preflight before profiling.</span><button className="dc-primary" disabled={source==='files'&&!files.length}>{source==='files'?'Import and profile':'Connect and profile'} <ArrowRight size={16}/></button></footer></form>:
  <main className="dc-ready"><span><Check size={28}/></span><p className="dc-eyebrow">CONNECTION SETUP</p><h2 id="dc-title">Your {selected.name} details are ready.</h2><p>The live credential exchange is not enabled in this demo. The complete connection and profiling path is preserved for the production workspace.</p><button className="dc-primary" onClick={onClose}>Return to workspace</button></main>}
 </section></div>;
}
