'use client';
import {RadarChart,Radar,PolarGrid,PolarAngleAxis,PolarRadiusAxis,PieChart,Pie,Cell,ScatterChart,Scatter,FunnelChart,Funnel,LabelList,ComposedChart,Area,Line,Bar,CartesianGrid,XAxis,YAxis,Tooltip,ResponsiveContainer,Legend} from 'recharts';
import {categoryRows,categoryTotals,categories,funnelData,chartData,chartDefaults,chartSummary,metricInfo,metricFormat,type Screen,type Metric} from '@/lib/analytics';
export default function DynamicChart({screen,reduced}:{screen:Screen;reduced:boolean}){
 const spec=screen.chart||chartDefaults(screen.view),rows=chartData(screen),summary=chartSummary(screen),first=spec.metrics[0];
 if(screen.display==='number')return <div className="an-scalar"><p className="an-kicker">{metricInfo[first].label}</p><div className="an-scalar-value">{metricFormat(first,summary[first])}</div><p className="an-context">September {spec.start}–{spec.end}, 2026 · demo data{first==='growth'&&rows.length>1?' · first-to-last change':''}</p></div>;
 if(screen.display==='table')return <><p className="an-kicker">THE DETAILS</p><h2>{spec.metrics.map(m=>metricInfo[m].label).join(' + ')}, day by day.</h2><p className="an-context">September {spec.start}–{spec.end}, 2026 · demo data</p><div className="an-table-wrap"><table className="an-table"><thead><tr><th>Date</th>{spec.metrics.map(m=><th key={m}>{metricInfo[m].label} ({metricInfo[m].unit})</th>)}{spec.previous&&<th>Previous sales (USD)</th>}</tr></thead><tbody>{rows.map(r=><tr key={r.day}><td>{r.day}</td>{spec.metrics.map(m=><td key={m}>{metricFormat(m,r[m])}</td>)}{spec.previous&&<td>{metricFormat('sales',r.previous)}</td>}</tr>)}</tbody></table></div></>;
 if(['pie','donut','horizontal','stacked','scatter','funnel','heatmap','histogram','radar'].includes(spec.kind)){
 const totals=categoryTotals(screen),split=categoryRows(screen),stages=funnelData(screen),second=spec.metrics[1]||'sales';
 const values=rows.map(r=>r[first]).filter((v):v is number=>v!==null),lo=Math.min(...values),hi=Math.max(...values),step=(hi-lo)/4||1,bins=Array.from({length:4},(_,i)=>({name:`${metricFormat(first,lo+i*step)}–${metricFormat(first,lo+(i+1)*step)}`,count:values.filter(v=>v>=lo+i*step&&(i===3?v<=hi:v<lo+(i+1)*step)).length}));
 const tooltip=<Tooltip contentStyle={{background:'#202922',border:'1px solid #46513f',borderRadius:12,color:'#fff'}}/>;
 return <><p className="an-kicker">{spec.kind==='histogram'?`${metricInfo[first].label} DISTRIBUTION`:spec.kind==='funnel'?'SHOPPING FUNNEL':spec.kind==='scatter'?`${metricInfo[first].label} × ${metricInfo[second].label}`:'SALES BY CATEGORY'}</p><h2>{spec.kind==='histogram'?'The shape of your numbers.':spec.kind==='funnel'?'From visits to orders.':spec.kind==='scatter'?'How the numbers move together.':'Where your sales come from.'}</h2><p className="an-context">September {spec.start}–{spec.end}, 2026 · demo data</p>
 <div className="an-special-chart" role="img" aria-label={spec.kind==='histogram'?bins.map(b=>`${b.name}: ${b.count} days`).join('; '):spec.kind==='funnel'?stages.map(d=>`${d.name}: ${d.value}`).join('; '):spec.kind==='scatter'?rows.map(r=>`${r.day}: ${metricFormat(first,r[first])}, ${metricFormat(second,r[second])}`).join('; '):totals.map(d=>`${d.name}: ${metricFormat('sales',d.value)}`).join('; ')}>
 {spec.kind==='heatmap'?<div className="an-heatmap"><div className="an-heat-row"><span/>{categories.map(c=><strong key={c.name}>{c.name}</strong>)}</div>{split.map(r=><div className="an-heat-row" key={r.day}><strong>{r.day}</strong>{categories.map(c=><span key={c.name} style={{background:`rgba(183,244,120,${.12+.88*r[c.name]/Math.max(...split.map(d=>d.Apparel))})`}}>{metricFormat('sales',r[c.name])}</span>)}</div>)}</div>:<ResponsiveContainer width="100%" height="100%">
 {spec.kind==='radar'?<RadarChart data={totals} outerRadius="75%"><PolarGrid stroke="#ffffff22"/><PolarAngleAxis dataKey="name" tick={{fill:'#a4afa6'}}/><PolarRadiusAxis tick={{fill:'#a4afa6'}}/><Radar dataKey="value" name="Sales (USD)" fill="#b7f478" fillOpacity={.3} stroke="#b7f478" isAnimationActive={!reduced}/>{tooltip}</RadarChart>:spec.kind==='histogram'?<ComposedChart data={bins} margin={{bottom:30,left:10,right:20}}><CartesianGrid stroke="#ffffff12"/><XAxis dataKey="name" tick={{fill:'#a4afa6',fontSize:10}} interval={0}/><YAxis allowDecimals={false} tick={{fill:'#a4afa6'}}/>{tooltip}<Bar dataKey="count" name="Days" fill="#b7f478" isAnimationActive={!reduced}/></ComposedChart>:spec.kind==='pie'||spec.kind==='donut'?<PieChart><Pie data={totals} dataKey="value" nameKey="name" innerRadius={spec.kind==='donut'?'55%':0} outerRadius="85%" paddingAngle={3} isAnimationActive={!reduced}>{totals.map(c=><Cell key={c.name} fill={c.color}/>)}</Pie><Tooltip formatter={v=>metricFormat('sales',Number(v))} contentStyle={{background:'#202922',border:'1px solid #46513f',borderRadius:12,color:'#fff'}}/><Legend/></PieChart>
 :spec.kind==='scatter'?<ScatterChart margin={{top:20,right:30,bottom:30,left:20}}><CartesianGrid stroke="#ffffff12"/><XAxis type="number" dataKey={first} name={metricInfo[first].label} tick={{fill:'#a4afa6'}} label={{value:`${metricInfo[first].label} (${metricInfo[first].unit})`,position:'bottom',fill:'#a4afa6'}}/><YAxis type="number" dataKey={second} name={metricInfo[second].label} tick={{fill:'#a4afa6'}} label={{value:`${metricInfo[second].label} (${metricInfo[second].unit})`,angle:-90,position:'insideLeft',fill:'#a4afa6'}}/>{tooltip}<Scatter data={rows} fill="#b7f478" isAnimationActive={!reduced}/></ScatterChart>
 :spec.kind==='funnel'?<FunnelChart>{tooltip}<Funnel data={stages} dataKey="value" nameKey="name" isAnimationActive={!reduced}><LabelList position="center" fill="#122018" dataKey="name"/></Funnel></FunnelChart>
 :<ComposedChart data={(spec.kind==='horizontal'?totals:split) as Record<string,string|number>[]} layout={spec.kind==='horizontal'?'vertical':'horizontal'} margin={{top:15,right:30,left:20,bottom:10}}><CartesianGrid stroke="#ffffff12"/><XAxis type={spec.kind==='horizontal'?'number':'category'} dataKey={spec.kind==='horizontal'?undefined:'day'} tick={{fill:'#a4afa6'}}/><YAxis type={spec.kind==='horizontal'?'category':'number'} dataKey={spec.kind==='horizontal'?'name':undefined} width={85} tick={{fill:'#a4afa6'}}/>{tooltip}{spec.kind==='horizontal'?<Bar dataKey="value" name="Sales (USD)" fill="#b7f478" isAnimationActive={!reduced}>{totals.map(c=><Cell key={c.name} fill={c.color}/>)}</Bar>:categories.map(c=><Bar key={c.name} dataKey={c.name} stackId="sales" fill={c.color} isAnimationActive={!reduced}/>)}<Legend/></ComposedChart>}
 </ResponsiveContainer>}</div>
 <div className="an-chart-key">{(spec.kind==='funnel'?stages:['scatter','histogram'].includes(spec.kind)?[]:totals).map(d=><span key={d.name}>{d.name}<strong>{spec.kind==='funnel'?d.value.toLocaleString():metricFormat('sales',d.value)}</strong></span>)}</div><p className="an-table-note">{spec.kind==='histogram'?'Daily values grouped into four equal-width bins. Counts represent days, not transactions.':spec.kind==='scatter'?'Each dot represents a day. Correlation does not establish causation.':spec.kind==='funnel'?'Cart and checkout counts are illustrative demo estimates; sessions and orders use the demo dataset.':'Category amounts are illustrative allocations of demo sales, consistent across chart types.'}</p></>;
 }
 return <><div className="an-result-top"><div><p className="an-kicker">{spec.metrics.map(m=>metricInfo[m].label).join(' + ').toUpperCase()}</p><div className="an-value">{metricFormat(first,summary[first])}</div><p className="an-context">September {spec.start}–{spec.end} · {rows.length} {rows.length===1?'day':'days'} · {first==='growth'?'first-to-last change':'demo data'}</p></div>{spec.metrics.length>1&&<div className="an-insight"><p className="an-kicker">{metricInfo[spec.metrics[1]].label.toUpperCase()}</p><h2 style={{color:metricInfo[spec.metrics[1]].color}}>{metricFormat(spec.metrics[1],summary[spec.metrics[1]])}</h2><p>Separate labeled axes preserve each metric’s units.</p></div>}</div>
 <div className="an-chart" role="img" aria-label={rows.map(r=>`${r.day}: ${spec.metrics.map(m=>`${metricInfo[m].label} ${metricFormat(m,r[m])}`).join(', ')}`).join('; ')}><ResponsiveContainer width="100%" height="100%"><ComposedChart data={rows} margin={{top:20,right:10,left:0,bottom:0}}><CartesianGrid vertical={false} stroke="#ffffff0f"/><XAxis dataKey="day" axisLine={false} tickLine={false} tick={{fill:'#a4afa6',fontSize:12}}/>{spec.metrics.map((m,i)=><YAxis key={m} yAxisId={m} orientation={i?'right':'left'} width={65} axisLine={false} tickLine={false} tick={{fill:metricInfo[m].color,fontSize:12}} tickFormatter={v=>metricInfo[m].unit==='%'?`${v}%`:metricInfo[m].unit==='USD'?`$${v>=1000?(v/1000)+'k':v}`:v>=1000?(v/1000)+'k':String(v)}/>)}<Tooltip contentStyle={{background:'#202922',border:'1px solid #46513f',borderRadius:12,color:'#fff'}} formatter={(value,name)=>{const m=name==='previous'?'sales':name as Metric;return [metricFormat(m,Number(value)),name==='previous'?'Sales · previous week':metricInfo[m].label];}}/><Legend formatter={v=>v==='previous'?'Sales · previous week':`${metricInfo[v as Metric].label} (${metricInfo[v as Metric].unit})`}/>{spec.previous&&<Line yAxisId="sales" dataKey="previous" stroke="#8b9784" strokeDasharray="5 6" dot={false} isAnimationActive={!reduced}/>}{spec.metrics.map(m=>spec.kind==='bar'?<Bar key={m} yAxisId={m} dataKey={m} fill={metricInfo[m].color} radius={[4,4,0,0]} maxBarSize={60} isAnimationActive={!reduced}/>:spec.kind==='line'?<Line key={m} yAxisId={m} dataKey={m} type="monotone" stroke={metricInfo[m].color} strokeWidth={3} dot={{r:4}} isAnimationActive={!reduced}/>:<Area key={m} yAxisId={m} dataKey={m} type="monotone" stroke={metricInfo[m].color} strokeWidth={3} fill={metricInfo[m].color} fillOpacity={.12} dot={rows.length===1} isAnimationActive={!reduced}/>)}</ComposedChart></ResponsiveContainer></div>
 <p className="an-table-note">{spec.metrics.includes('conversion')?'Conversion = orders ÷ sessions. ':''}{spec.metrics.includes('growth')?'Growth is measured against the preceding available day; September 9 has no baseline. ':''}{spec.previous?'Dashed line: matching days in the previous week. ':''}Ask to change the metric, dates, or chart type.</p></>;
}
