import {backend,sqlQuery} from './backend.mjs';
import {salesPresentation} from './reporting.mjs';
const offset=(date,days)=>new Date(Date.parse(date+'T12:00:00Z')+days*86400000).toISOString().slice(0,10);
export function decompose(current,baseline){
 const tb=baseline.sessions,tc=current.sessions,cb=tb?baseline.orders/tb:0,cc=tc?current.orders/tc:0,ab=baseline.orders?baseline.revenue/baseline.orders:0,ac=current.orders?current.revenue/current.orders:0;
 const effects=[{driver:'Traffic',effect:(tc-tb)*cb*ab,baseline:tb,current:tc,unit:'sessions'},{driver:'Completed conversion',effect:tc*(cc-cb)*ab,baseline:cb*100,current:cc*100,unit:'%'},{driver:'Average order value',effect:tc*cc*(ac-ab),baseline:ab,current:ac,unit:'USD'}];
 return {effects,unexplained:current.revenue-baseline.revenue-effects.reduce((s,x)=>s+x.effect,0),method:'Sequential traffic → completed conversion → average order value decomposition. Mathematical contribution, not causal proof.'};
}
let cached,until=0;
export async function salesIntelligence(){
 const schema=await backend('/schema');if(cached?.datasetVersion===schema.version&&Date.now()<until)return cached;
 const date=schema.period.end;if(!/^\d{4}-\d{2}-\d{2}$/.test(date))throw Error('Invalid database period');const baselineDate=offset(date,-7),start=offset(date,-13);
 const query=async sql=>{const r=await sqlQuery(sql);if(r.datasetVersion&&r.datasetVersion!==schema.version)throw Error('Dataset updated during analysis; retry');return r.rows;};
 const daily=await query(`WITH revenue AS (SELECT order_date date,SUM(CASE WHEN status='completed' THEN net_amount ELSE 0 END)::DOUBLE revenue,COUNT(*) FILTER(WHERE status='completed')::INTEGER orders,COUNT(*)::INTEGER placed_orders,COUNT(*) FILTER(WHERE status='cancelled')::INTEGER cancelled_orders FROM orders WHERE order_date BETWEEN DATE '${start}' AND DATE '${date}' GROUP BY order_date),traffic AS(SELECT session_date date,COUNT(*)::INTEGER sessions FROM sessions WHERE session_date BETWEEN DATE '${start}' AND DATE '${date}' GROUP BY session_date) SELECT r.date::VARCHAR date,r.revenue,r.orders,r.placed_orders,r.cancelled_orders,t.sessions FROM revenue r JOIN traffic t USING(date) ORDER BY r.date`);
 const current=daily.find(x=>x.date===date),baseline=daily.find(x=>x.date===baselineDate);if(!current||!baseline)throw Error('Comparable complete dates unavailable');
 const metricSql=(name,from,amount)=>`SELECT ${name} AS "label", SUM(CASE WHEN o.order_date=DATE '${date}' THEN ${amount} ELSE 0 END)::DOUBLE AS "current", SUM(CASE WHEN o.order_date=DATE '${baselineDate}' THEN ${amount} ELSE 0 END)::DOUBLE AS "baseline" FROM ${from} WHERE o.status='completed' AND o.order_date IN (DATE '${date}',DATE '${baselineDate}') GROUP BY ${name} ORDER BY ("current"-"baseline")`;
 const categories=await query(metricSql('cat.category_name','orders o JOIN order_items oi USING(order_id) JOIN products p USING(product_id) JOIN categories cat USING(category_id)','oi.net_amount'));
 const regions=await query(metricSql('r.region_name','orders o JOIN customers c USING(customer_id) JOIN regions r USING(region_id)','o.net_amount'));
 const channels=await query(metricSql('o.channel','orders o','o.net_amount'));
 const traffic=await query(`SELECT traffic_source AS "label",COUNT(*) FILTER(WHERE session_date=DATE '${date}')::INTEGER AS "current",COUNT(*) FILTER(WHERE session_date=DATE '${baselineDate}')::INTEGER AS "baseline" FROM sessions WHERE session_date IN(DATE '${date}',DATE '${baselineDate}') GROUP BY traffic_source ORDER BY("current"-"baseline")`);
 const devices=await query(`SELECT s.device AS "label",COUNT(*) FILTER(WHERE s.session_date=DATE '${date}')::INTEGER current_sessions,COUNT(*) FILTER(WHERE s.session_date=DATE '${baselineDate}')::INTEGER baseline_sessions,COUNT(*) FILTER(WHERE s.session_date=DATE '${date}' AND o.status='completed')::INTEGER current_completed,COUNT(*) FILTER(WHERE s.session_date=DATE '${baselineDate}' AND o.status='completed')::INTEGER baseline_completed FROM sessions s LEFT JOIN orders o USING(order_id) WHERE s.session_date IN(DATE '${date}',DATE '${baselineDate}') GROUP BY s.device ORDER BY s.device`);
 const products=await query(`SELECT p.product_name AS "name",cat.category_name AS "category",SUM(oi.quantity)::INTEGER AS "units",SUM(oi.net_amount)::DOUBLE AS "revenue" FROM orders o JOIN order_items oi USING(order_id) JOIN products p USING(product_id) JOIN categories cat USING(category_id) WHERE o.status='completed' AND o.order_date=DATE '${date}' GROUP BY p.product_id,p.product_name,cat.category_name ORDER BY revenue DESC LIMIT 3`);
 const events=await query(`SELECT event_name,summary,source_type,start_date::VARCHAR start_date,end_date::VARCHAR end_date FROM business_events WHERE start_date<=DATE '${date}' AND end_date>=DATE '${date}' ORDER BY event_id DESC LIMIT 10`);
 for(const rows of [categories,regions,channels]){const total=rows.reduce((s,x)=>s+x.current-x.baseline,0);if(Math.abs(total-(current.revenue-baseline.revenue))>.01)throw Error('Breakdown failed revenue reconciliation');}
 const change=current.revenue-baseline.revenue,attribution=decompose(current,baseline);
 cached={synthetic:true,currency:'USD',datasetVersion:schema.version,dataThrough:date,baselineDate,comparison:'Latest complete day versus the same weekday one week earlier',generatedAt:new Date().toISOString(),source:{service:'liveanalyst-duckdb',project:'striking-loop-447915-q3',period:schema.period,totalRows:schema.totalRows,updatedAt:schema.updatedAt||null,generation:schema.generation||null},current,baseline,change,changePct:baseline.revenue?change/baseline.revenue*100:null,attribution,daily,categories,regions,channels,traffic,devices,products,events,interpretation:change<0?'Revenue fell versus the same weekday last week. Inspect measured driver effects and segment changes.':'Revenue is level or higher versus the same weekday last week. Negative segment movements can still deserve investigation.',caveat:'All records are synthetic. Segment changes overlap across dimensions and must not be added together. Scenario events are context, not proven causes. No inventory availability or payment-error measurements exist.'};cached.presentation=salesPresentation(cached);until=Date.now()+30000;return cached;
}
